### ISSUE TITLE
[QUESTION] Getting `A subscriber that is no longer registered has attempted to unsubscribe`

### ISSUE THREAD

**Issue by afvr94** [robtaussig/react-use-websocket#49] opened 2020-06-12 15:18 UTC
Hello, 

First of all great library and very useful. So, I'm getting a lot of this type of error `A subscriber that is no longer registered has attempted to unsubscribe` and wanted to know why? I saw the source code but still can't understand. Do I have to use the same options for every shared web socket?

Example of first initialized web socket, this is called in my main app file.
```
const { sendJsonMessage, lastJsonMessage } = useWebSocket(WS_URL, {
    share: true,
    shouldReconnect: (closeEvent) => closeEvent.code === WS_CLOSED,
    // will attempt to reconnect 20 * WS_RECONNECT_INTERVAL_MS
    reconnectAttempts: WS_RECONNECT_ATTEMPTS,
    reconnectInterval: WS_RECONNECT_INTERVAL_MS,
    retryOnError: true,
  });
```

And I have some other web socket in components like this:

```
const { lastJsonMessage } = useWebSocket(WS_URL, {
    share: true,
  });
```

Thanks for your help and for the library 🚀

**Comment by robtaussig** [comment] 2020-06-12 23:24
Hi @afvr94,

First, thank you for the kind words:)

And welcome @pankajgupta1 (who I believe is having a similar problem and commented in another thread)

So, this stumped me for a while as I tried to reproduce it, but I believe I have found the problem(s), and if I'm right, there are quite a few issues with how I was handling shared websockets. First, to illustrate a scenario:

```tsx
import React, { useEffect } from 'react';
import { render } from 'react-dom';
import useWebSocket from 'react-use-websocket';

const WS_URL = 'wss://echo.websocket.org';

const ChildSocket = () => {
  console.log('child body');
  const {} = useWebSocket(WS_URL, {
    share: true,
  });

  useEffect(() => {
    console.log('child effect');
  }, []);

  return (
    <div/>
  );
};

const ParentSocket = () => {
  console.log('parent body');
  const {} = useWebSocket(WS_URL, {
    share: true,
    shouldReconnect: () => true,
  });

  useEffect(() => {
    console.log('parent effect');
  }, []);

  return (
    <div/>
  );
};

render(ParentSocket, document.getElementById('root'))
```
There's a few things going on above. When the app starts, 4 things will be logged to console:

```
parent body
child body
child effect
parent effect
```
This makes sense (although I hadn't considered it when writing this library) since useEffect triggers *after* the component renders, and even though the parent function is called first, the child component mounts/renders first, and like a stack, the child will resolve first (including the useEffect). The hook is equally affected since it does all of the heavy lifting in a useEffect.

If we look back at the example, because the child component is the first to mount, it is the first component to instantiate the shared websocket, and because it has not set `shouldReconnect` in its options, when the websocket closes, it will not attempt to reconnect (even though the parent component clearly wants it to reconnect).

I started doing some other tests with shared websockets, and in particular iterable components that can be added and removed, each subscribing to the same websocket. And what I found was that when I removed the first element, which would cause all of the other elements to shift up by one position, React considered it a complete redraw (even though each component had a key that was not dependent on order), and every component unmounted and a new component mounted. What resulted was the list of subscribers for a given url will empty out, triggering the closing and cleanup of that websocket. Long story short, the cleanup function was being called twice.

Anyhow, I decided to refactor the code that involves shared websockets as I decided it was fundamentally flawed if it depended on the order by which the shared components mount. And it also shouldn't matter to one component what the options set by another component are, besides both using the share property and both using the same url. Given the amount of changes, I felt this should have a beta release first (already released now under react-use-websocket@2.0.3-b.3).

Here is the commit with the changes: https://github.com/robtaussig/react-use-websocket/commit/1567770d28ee79aa380ec540609023516858c99f

Thanks again to both of you and let me know if this fixes your problem!

**Comment by afvr94** [comment] 2020-06-13 22:39
Thank you for your response and explanation. Makes sense that that is making show up the error. Will be testing out `2.0.3-b.3` and will report back if I encounter any bugs. Thank you again.

**Comment by robtaussig** [comment] 2020-06-13 22:41
Hi @afvr94,

Please try 2.0.3-b.4. I normally develop on a mac, but did so on a PC last night. The build script didn't work and I accidentally published the uncompiled source

**Comment by pankajgupta1** [comment] 2020-06-15 06:50
Hi @robtaussig thanks for your response. Actually my problem is not this. My problem is
1) I am, using shared websocket.
2) when I reload the app in ios simulator, then connection not made automatically.
3) I have to close the app in simulator, and then reopen, then connection is made.

Also I tried the above version 2.0.3-b.4., but this giving error, which is in attached screenshot
<img width="379" alt="Screenshot 2020-06-15 at 12 19 47 PM" src="https://user-images.githubusercontent.com/44722747/84626338-87b80180-af02-11ea-89e0-65b9839eca22.png">

**Comment by afvr94** [comment] 2020-06-15 12:56
Hi @robtaussig, 

Been testing out `2.0.3-b.4` and the socket does reconnect but I do not receive any message through it (neither parent and child socket). When I do a full refresh is when I start getting messages again. Let me now if you need anything from me. Thanks.

**Comment by robtaussig** [comment] 2020-06-15 13:44
@pankajgupta1 

I'm sorry to ask this of you, but could you try deleting node_modules and reinstalling? I removed the '/add-subscriber' file completely in 2.0.3-b.4, so it shouldn't be referenced in any dependency-trees.

**Comment by robtaussig** [comment] 2020-06-15 13:49
> Hi @robtaussig,
> 
> Been testing out `2.0.3-b.4` and the socket does reconnect but I do not receive any message through it (neither parent and child socket). When I do a full refresh is when I start getting messages again. Let me now if you need anything from me. Thanks.

Hi @afvr94 ,

If you check the network log in dev-tools and inspect the websocket connection, can you confirm whether the new (reconnected) websocket is receiving messages (as opposed to it receiving a message but not passing it on to the component(s))? Also, in order to receive messages, is there a step that is required when the websocket first opens (like subscribing to a topic, etc) that perhaps is not being properly repeated when it reconnects? I'm not trying to imply that you are doing anything wrong, but I just want to get a better idea of where I should start looking.

**Comment by afvr94** [comment] 2020-06-15 14:02
Hi @robtaussig, I deleted my comment because I have something wrong with my code when socket gets reconnected. Will post back when I get all fixed up. Thanks.

**Comment by pankajgupta1** [comment] 2020-06-17 05:40
> @pankajgupta1
> 
> I'm sorry to ask this of you, but could you try deleting node_modules and reinstalling? I removed the '/add-subscriber' file completely in 2.0.3-b.4, so it shouldn't be referenced in any dependency-trees.

yes now this build error not happening. Thanks.

**Comment by afvr94** [comment] 2020-06-18 22:25
Hi @robtaussig, been testing out `2.0.3-b.4` and everything seems to be working as expected. If I find something will let you know. Thank you so much.

**Comment by robtaussig** [comment] 2020-06-19 00:53
Great. Bumped to 2.0.3. Thanks for your continued feedback!

**Closed by robtaussig** 2020-06-19 00:53 UTC
