### ISSUE TITLE
Sending message in onOpen

### ISSUE THREAD

**Issue by mohsenasm** [robtaussig/react-use-websocket#32] opened 2020-03-25 08:55 UTC
Hi,
How can we sendMessage when receiving onOpen event?

```
import useWebSocket from 'react-use-websocket';

const STATIC_OPTIONS = useMemo(() => ({
  onOpen: (event) => {
    console.log('opened');
    // send a message to server
  }, 
}), []);

const [sendMessage, lastMessage, readyState, getWebSocket] = useWebSocket('wss://echo.websocket.org', STATIC_OPTIONS);
```
We cannot use `sendMessage` function because it will be defined after STATIC_OPTIONS memo and so `sendMessage` cannot be placed into STATIC_OPTIONS dependency list (as eslint's exhaustive-deps says).

My first try is using `event.currentTarget.send`, but I am not sure this is a good usage or not.

**Comment by robtaussig** [comment] 2020-04-07 20:03
Hi @mohsenasm,

This is a good question, and something I've had to hack around in the past. I actually like your solution a lot better than I do my own, so I will refrain from polluting the solution pool. That said, this does kind of go against the design philosophy of limiting direct access to the underlying websocket (as it may be shared, wrapped, etc) -- what do you think of me adding the sendMessage function as a second param to the onOpen handler? WebSocket#onopen only has one parameter (the event), so this wouldn't be competing against conventional use.

**Comment by robtaussig** [comment] 2020-04-14 16:02
Hi @mohsenasm,

Apologies for the delay and thank you for your patience. I merged the change that provides sendMessage as a second argument to the onOpen handler. While not required for this particular feature, I also implemented a message queue so that any messages sent prior to the websocket opening are queued up and sent once the websocket transitions to the Open readyState.

3927b53

**Closed by robtaussig** 2020-04-14 16:02 UTC

**Comment by mohsenasm** [comment] 2020-04-14 16:22
Thanks!

I'm sorry, but I prefer using web socket connection in its full potential.
There is another problem too. we cannot close connection, atleast with `getWebSocket` (there may be another way but I dont know).

By the way, now I am using [my own useWebSocket](https://gist.github.com/mohsenasm/5b01a8cc82e9140df8a86860bd16d108) :).
Wish You Well.

**Comment by robtaussig** [comment] 2020-04-14 16:42
Fair enough @mohsenasm!

Coincidentally, I just addressed another issue caused by limiting access to the underlying websocket. As such, I modified the behavior of getWebsocket so that it provides the underlying websocket directly, but only if it is not shared. The reason for this is I didn't want it to become a wild-west if multiple components are sharing the same websocket, but all of them are free to close/set properties on it:)

https://github.com/robtaussig/react-use-websocket/issues/35

10cedea

**Comment by robtaussig** [comment] 2020-04-14 16:57
@mohsenasm,

I hope you don't mind some unsolicited feedback, but in your `reconnect` function, it calls itself in both the `onerror` and `onclose` handler of the reconnected websocket. In almost all cases, `close` will be called after any error events, and so your websocket will be instantiated twice after most errors. This can create other bugs depending on whether/how you access the websocket on the onOpen event, as this will also now be called twice after an error (assuming both reconnect attempts succeed), and both times with different websockets.

Another piece of advice that I've learned the hard way is to distinguish between intentional close events and unintentional close events. Without doing so, it is impossible to completely disconnect a websocket as there is no way for it to close without a new one being created.

**Comment by mohsenasm** [comment] 2020-04-15 06:57
Thanks! Nice comment!
I Fixed that.

**Comment by joealden** [comment] 2022-05-20 11:59
@robtaussig it looks like it's no longer possible to access `sendMessage` in the `onOpen` handler. If so, what was the reasoning behind removing this?

**Comment by vhpoet** [comment] 2023-03-09 00:47
@robtaussig +1 to the above question.

**Comment by magoz** [comment] 2024-01-20 11:28
I have the same request. 
Is there a way to call `sendMessage` in the `onOpen` handler @robtaussig?

**Comment by denvudd** [comment] 2025-01-10 13:54
+1
Hey, any updates on this?

**Comment by michaelboyles** [comment] 2025-12-02 17:10
Memoizing the options here provides no performance advantage, so the answer is simple: remove the memo 

```
const { sendMessage } = useWebSocket({
	url: URL,
	onOpen() {
		sendMessage("hello world")
	},
})
```
